<?include ("../class/conect.php"); include ("../class/funciones.php"); $tipo_nomina=$_GET["tipo_nomina"];$ope=$_GET["ope"]; $codigo_mov=$_GET["codigo_mov"]; $password=$_GET["password"]; $user=$_GET["user"];$dbname=$_GET["dbname"]; $fecha_desde=""; $fecha_hasta=""; $nro_semanas="";
$conn=pg_connect("host=".$host." port=".$port." password=".$password." user=".$user." dbname=".$dbname."");  $campo502="NNNNNNNNNNNNNNNNNNN";
$StrSQL="select frecuencia,ultima_fecha,proxima_fecha,nro_semana from nom001 where tipo_nomina='$tipo_nomina'";$resultado=pg_query($StrSQL); $filas=pg_num_rows($resultado);
if($filas>0){$registro=pg_fetch_array($resultado); $frec=$registro["frecuencia"]; $ultima_fecha=$registro["ultima_fecha"]; $proxima_fecha=$registro["proxima_fecha"]; $num_semana=$registro["nro_semana"]; $fecha_desde=formato_ddmmaaaa($ultima_fecha); $fecha_hasta=formato_ddmmaaaa($proxima_fecha); $nro_semanas=0;
  $fecha_desde=nextDate($fecha_desde,1);  if($frec=="M"){$fecha_hasta=colocar_udiames($fecha_desde);} if($frec=="S"){$fecha_hasta=nextDate($fecha_desde,6);$nro_semanas=$num_semana+1;} if($frec=="Q"){$dia=substr($fecha_desde,0,2); $fecha_hasta=colocar_udiames($fecha_desde); if($dia=='01'){$fecha_hasta=nextDate($fecha_desde,14);}} }
$StrSQL="Select fecha_p_desde,fecha_p_hasta,fecha_desde,fecha_hasta,nro_semana from NOM017 where (tipo_nomina='$tipo_nomina')";$resultado=pg_query($StrSQL);$filas=pg_num_rows($resultado); if($filas>0){$registro=pg_fetch_array($resultado); $fecha_desde=$registro["fecha_p_desde"]; $fecha_hasta=$registro["fecha_p_hasta"]; $fecha_desde=formato_ddmmaaaa($fecha_desde); $fecha_hasta=formato_ddmmaaaa($fecha_hasta);} 
$sfecha=formato_aaaammdd($fecha_desde); 
pg_close();      ?>
<table width="946"><tr>
<td width="106"><span class="Estilo5">FECHA DESDE : </span></td> <td width="120"><span class="Estilo5"><input name="txtfecha_desde" type="text" id="txtfecha_desde"  size="10" maxlength="10" onFocus="encender(this)" onBlur="apagar(this)" value="<?echo $fecha_desde?>"> </span></td>
<td width="100"><span class="Estilo5">FECHA HASTA : </span></td>  <td width="130"><span class="Estilo5"> <input name="txtfecha_hasta" type="text" id="txtfecha_hasta"  size="10" maxlength="10" onFocus="encender(this)" onBlur="apagar(this)" value="<?echo $fecha_hasta?>"> </span></td>
<td width="250"><span class="Estilo5"></span></td>    <td width="240"><span class="Estilo5"> </span></td>
</tr> </table>