<?include ("../class/conect.php");  include ("../class/funciones.php");
$tipo_nomina=$_POST["txttipo_nomina"]; $cod_concepto=$_POST["txtcod_concepto"]; $cod_empleado=$_POST["txtcod_empleado"]; $criterio=$_POST["txtcriterio"]; $calculable="SI"; $frecuencia="0"; $prestamo="S"; $fecha_ini=$_POST["txtfecha_ini"]; $fecha_exp=$_POST["txtfecha_exp"];
$activo="SI"; $activo=$_POST["txtactivo"]; $cantidad=0; $monto=$_POST["txtmonto"]; $acumulado=$_POST["txtacumulado"]; $saldo=$_POST["txtsaldo"]; $monto_prestamo=$_POST["txtmonto_prestamo"]; $nro_cuotas=$_POST["txtnro_cuotas"]; $nro_cuotas_c=$_POST["txtnro_cuotas_c"];
$fecha_hoy=asigna_fecha_hoy(); $monto_prestamo=formato_numero($monto_prestamo); if(is_numeric($monto_prestamo)){$monto_prestamo=$monto_prestamo;}else{$monto_prestamo=0;} $monto=formato_numero($monto); if(is_numeric($monto)){$monto=$monto;}else{$monto=0;}  $nro_cuotas=formato_numero($nro_cuotas); if(is_numeric($nro_cuotas)){$nro_cuotas=$nro_cuotas;}else{$nro_cuotas=0;}
$acumulado=formato_numero($acumulado); if(is_numeric($acumulado)){$acumulado=$acumulado;}else{$acumulado=0;} $saldo=formato_numero($saldo); if(is_numeric($saldo)){$saldo=$saldo;}else{$saldo=0;}  $nro_cuotas_c=formato_numero($nro_cuotas_c); if(is_numeric($nro_cuotas_c)){$nro_cuotas_c=$nro_cuotas_c;}else{$nro_cuotas_c=0;}
$equipo = getenv("COMPUTERNAME"); $minf_usuario=$usuario_sia." ".$equipo." ".date("d/m/y H:i a");echo "ESPERE POR FAVOR MODIFICANDO....","<br>";
$url="Det_prestamo.php?criterio=".$criterio; $conn=pg_connect("host=".$host." port=".$port." password=".$password." user=".$user." dbname=".$dbname."");  $error=0;
if (pg_ErrorMessage($conn)){$error=1; ?><script language="JavaScript">muestra('OCURRIO UN ERROR CONECTANDO LA BASE DE DATOS');</script><?}
 else{ $sSQL="Select cod_concepto,cantidad,monto,activo,calculable,frecuencia,nro_cuotas,monto_prestamo,nro_cuotas_c from NOM011 WHERE tipo_nomina='$tipo_nomina' and cod_empleado='$cod_empleado' and cod_concepto='$cod_concepto'"; $resultado=pg_query($sSQL);  $filas=pg_num_rows($resultado);
   if($filas==0){$error=1; ?> <script language="JavaScript"> muestra('ASIGNACION DE CONCEPTO NO EXISTE');</script><? } else{$registro=pg_fetch_array($resultado); $acantidad=$registro["nro_cuotas"]; $amonto=$registro["monto"]; $aprestamo=$registro["monto_prestamo"]; $anro_cuotas_c=$registro["nro_cuotas_c"]; }
   if($error==0){$sSQL="Select cod_concepto from NOM002 WHERE tipo_nomina='$tipo_nomina' and cod_concepto='$cod_concepto'"; $resultado=pg_query($sSQL);  $filas=pg_num_rows($resultado); if($filas==0){$error=1; ?> <script language="JavaScript"> muestra('CODIGO DE CONCEPTO NO EXISTE');</script><? }}
   if($error==0){$sSQL="Select tipo_nomina,descripcion,con_sue_bas,con_compen,g_orden_pago,frecuencia from NOM001 WHERE tipo_nomina='$tipo_nomina'"; $resultado=pg_query($sSQL); $filas=pg_num_rows($resultado); if($filas==0){$error=1;?><script language="JavaScript">muestra('TIPO DE NOMINA NO EXISTE');</script><?}else{$registro=pg_fetch_array($resultado); $g_orden_pago=$registro["g_orden_pago"]; $frec_nom=$registro["frecuencia"]; $cod_conc_s=$registro["con_sue_bas"]; $cod_conc_c=$registro["con_compen"];}}
   if($error==0){if(checkData($fecha_ini)=='1'){$error=0;} else{$error=1; ?> <script language="JavaScript">muestra('FECHA DESDE NO ES VALIDA');</script><?}}
   if($error==0){if(checkData($fecha_exp)=='1'){$error=0;} else{$error=1; ?> <script language="JavaScript">muestra('FECHA HASTA NO ES VALIDA');</script><?}}
   if($error==0){if($nro_cuotas<=0){$error=1; ?> <script language="JavaScript">muestra('NUMERO DE CUOTAS NO ES VALIDA');</script><?}}
   if($error==0){ if ($gnomina=="00"){$error=0;} else {  if($tipo_nomina<>$gnomina) {$error=1; ?> <script language="JavaScript"> muestra('TIPO DE NOMINA NO ACTIVA PARA EL USUARIO');</script><?}  } } 
   if($error==0){if($monto_prestamo<=0){$error=1; ?> <script language="JavaScript">muestra('MONTO DEL PRESTAMO NO ES VALIDO');</script><?}}
   if($error==0){if($monto<=0){$error=1; ?> <script language="JavaScript">muestra('MONTO DE LA CUOTA NO ES VALIDO');</script><?}}
   if($error==0){$sql="SELECT NOM006.cod_empleado,NOM006.tipo_nomina,NOM006.fecha_ingreso,NOM006.cod_categoria FROM NOM006 Where cod_empleado='$cod_empleado'"; $resultado=pg_query($sql);  $filas=pg_num_rows($resultado); if($filas==0){$error=1;?> <script language="JavaScript"> muestra('CODIGO DE TRABAJADOR NO EXISTE');</script><? }
     else{$registro=pg_fetch_array($resultado); $nom_emp=$registro["tipo_nomina"]; if($tipo_nomina!=$nom_emp){$error=1;?><script language="JavaScript"> muestra('TRABAJADOR NO PERTENECE A ESTA NÓMINA');</script><? } } }
   if($error==0){$sfecha=formato_aaaammdd($fecha_hoy); $cantidad=1; $activo="SI";
    $sSQL="SELECT ACT_PRESTAMO_NOM011('$tipo_nomina','$cod_empleado','$cod_concepto',$cantidad,$monto,'$fecha_ini','$fecha_exp','$activo','$calculable',$acumulado,$saldo,'$prestamo',$monto_prestamo,$nro_cuotas,$nro_cuotas_c)";
    $resultado=pg_exec($conn,$sSQL); $error=pg_errormessage($conn); $error="ERROR GRABANDO: ".substr($error, 0, 61); if (!$resultado){?><script language="JavaScript">muestra('<? echo $error; ?>');</script><?}else{$error=0;?><script language="JavaScript">muestra('MODIFICO EXITOSAMENTE');</script><?
    $desc_doc="PRESTAMO, TIPO NOMINA:".$tipo_nomina.", CODIGO TRABAJADOR:".$cod_empleado.", CODIGO CONCEPTO:".$cod_concepto.", CUOTAS:".$acantidad.", MONTO CUOTA:".$amonto.", MONTO PRESTAMO:".$aprestamo.", CUOTAS CANCELADAS:".$anro_cuotas_c; $resultado=pg_exec($conn,"SELECT INCLUYE_SIA004('04','$usuario_sia','$usuario_sia','$equipo','Modifico','$sfecha','$desc_doc')");
    $error=pg_errormessage($conn); $error=substr($error, 0, 61);  if (!$resultado){?><script language="JavaScript">muestra('<?echo $error;?>');</script><? }}
  }
}pg_close();  if($error==0){?><script language="JavaScript">document.location ='<? echo $url; ?>';</script><?}else{?><script language="JavaScript">history.back();</script><?}?>