<?include ("../class/conect.php"); include ("../class/funciones.php"); $login=$_POST["txtLoginu"];$clave=$_POST["txtClaveu"]; $nombre=$_POST["txtNombre"]; $cargo=$_POST["txtCargo"];$login=strtoupper($login); $clave=strtoupper($clave); $nombre=strtoupper($nombre); $tclave=$clave; $tusuario=$login;  $tclave=eliminar_car_claves($tclave); $tusuario=eliminar_car_claves($tusuario);  $departamento=$_POST["txtDepartamento"]; $cat_prog=$_POST["txtCat_prog"];$cod_almacen=$_POST["txtCod_Almacen"]; $unidad_sol=$_POST["txtUnidad_Sol"];$equipo = getenv("COMPUTERNAME"); $MInf_Usuario = $equipo." ".date("d/m/y H:i a");echo "ESPERE POR FAVOR INCLUYENDO....","<br>"; $url="usuarios.php";
$conn=pg_connect("host=".$host." port=".$port." password=".$password." user=".$user." dbname=".$dbname."");
if (pg_ErrorMessage($conn)) { ?> <script language="JavaScript"> muestra('OCURRIO UN ERROR CONECTANDO LA BASE DE DATOS'); </script> <?}
 else{  $tipo_u="N"; $error=0; $sql="SELECT campo103 FROM sia001 where campo101='$usuario_sia'"; $resultado=pg_exec($conn,$sql);$filas=pg_numrows($resultado);  $tipo_u="U";
  if ($filas>0){$registro=pg_fetch_array($resultado); $tipo_u=$registro["campo103"]; if($tipo_u=="A"){$error=0;}else{$error=1;} } else{$error=1;}  if($error==1){?> <script language="JavaScript"> muestra('NO TIENE DERECHOS PARA ESTA OPCION'); </script>  <? }
  if($error==0){ if($tusuario==$login){ $error=0;}else{$error=1; ?> <script language="JavaScript"> muestra('LOGIN NO VALIDO'); </script> <?} } if($error==0){ if($tclave==$clave){ $error=0;}else{$error=1;  ?><script language="JavaScript"> muestra('CLAVE NO VALIDA'); </script> <?} }
  if($error==0){$sSQL="Select * from SIA001 WHERE campo101='$login'";   $resultado=pg_exec($conn,$sSQL);  $filas=pg_numrows($resultado);
    if ($filas>0){?> <script language="JavaScript"> muestra('USUARIO YA EXISTE'); </script>  <? }
     else{ $sSQL="SELECT ACTUALIZA_SIA001(1,'$login','$clave','U','$nombre','$cargo','$departamento','$cat_prog','$cod_almacen','','','$unidad_sol','','','','')";$resultado=pg_exec($conn,$sSQL);
       $error=pg_errormessage($conn);$error=substr($error, 0, 61); if (!$resultado){ ?> <script language="JavaScript"> muestra('<? echo $error; ?>'); </script> <? } else{?><script language="JavaScript">muestra('INCLUYO EXITOSAMENTE');</script><? }
  } }
} pg_close();if($error==0){?><script language="JavaScript">document.location ='<? echo $url; ?>';</script><?}else{?><script language="JavaScript">history.back();</script><?}?>
